version: "3.3"

services:
  youlan-admin:
    image: youlan-admin:latest
    restart: always
    container_name: youlan-admin
    hostname: youlan-admin
    ports:
      - "4085:4085"
    volumes:
      - ./youlan-admin/logs:/application/logs
    environment:
      - TZ=Asia/Shanghai
      - JAR_OPTS=-Dspring.profiles.active=prod
      - JVM_OPTS=-XX:+UseStringDeduplication -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:+UseParallelOldGC