version: "3.3"

services:
  mysql:
    image: mysql:8.1
    restart: always
    container_name: mysql-prod
    hostname: mysql-prod
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql-files:/var/lib/mysql-files
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime
    environment:
      - MYSQL_ROOT_PASSWORD=youlan@123
  redis:
    image: redis:7.2.1
    restart: always
    container_name: redis-prod
    hostname: redis-prod
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    environment:
      - TZ=Asia/Shanghai
    command: [ "redis-server", "/etc/redis/redis.conf" ]