--- # Redis配置
spring:
  redis:
    host: 121.40.113.151
    port: 32379
    database: 80
    password: Lechou@123
    # 链接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中最小空闲连接
        min-idle: 0
        # 连接池中最大空闲连接
        max-idle: 8
        # 连接池中最大连接数
        max-active: 8
        # 连接池最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1ms

--- # 数据库配置
spring:
  # 数据库配置
  datasource:
    # 数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 数据源驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 动态数据源配置
    dynamic:
      # 设置默认的数据源或者数据源组，默认值master
      primary: master
      # 严格模式，匹配不到数据源则报错
      strict: true
      # 数据源
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.27.240.148:13308/youlan-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: basic
          password: Lechou@123
    # hikari配置
    hikari:
      # 最大连接池数
      maximum-pool-size: 20
      # 最小空闲线程数
      minimum-idle: 10
      # 连接超时时间
      connection-timeout: 30000
      # 校验超时时间
      validation-timeout: 5000
      # 空闲连接最大存活时间，默认10分钟
      idle-timeout: 600000
      # 连接池中连接最长生命周期，0为无限生命周期，默认30分钟
      max-lifetime: 1800000
      # 连接测试语句
      connection-test-query: SELECT 1
      # 多久检查一次连接的活性
      keepalive-time: 30000

# MyBatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl