--- # Redis配置
spring:
  redis:
    # redis地址
    host: localhost
    # redis端口
    port: 6379
    # redis逻辑数据库
    database: 0
    # redis密码
    password: youlan@123

--- # 数据库配置
spring:
  # 数据库配置
  datasource:
    # 动态数据源配置
    dynamic:
      # 数据源
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/youlan-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true}youlan-boot?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          username: root
          password: youlan@123

# MyBatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

--- # 插件模块
youlan:
  pay:
    # 是否启用回调(只有接收回调的服务才需要开启)
    notify-enabled: false
    # 是否启用支付记录同步(启用后将会定期向支付平台同步支付记录和支付订单状态)
    record-sync-enabled: false
    # 是否启用支付订单过期(启用后将会定期关闭过期的支付订单)
    order-expire-enabled: false
    # 是否启用退款订单同步(启用后将会定期向支付平台同步退款订单状态)
    refund-order-sync-enabled: false