--- # 后台管理模块
youlan:
  admin:
    # sa-token配置
    sa-token:
      exclude-path-patterns:
        # 静态资源相关
        - /*.html
        - /**/*.html
        - /*.css
        - /**/*.css
        - /*.js
        - /**/*.js
        # swagger相关
        - /*/api-docs
        - /*/api-docs/**

--- # 系统模块
youlan:
  system:
    # 验证码
    captcha:
      # 验证码类型(LINE-线条干扰 CIRCLE-圆圈干扰 SHEAR-扭曲干扰)
      captcha-type: CIRCLE
      # 验证码内容类型(CHAR-字符类型 NUMBER-数字类型 CHAR_NUMBER-字符+数字类型 MATH-四则运算类型)
      captcha-code-type: MATH
      # 验证码长度
      captcha-code-len: 5
    # 存储
    storage:
      # 文件存储根路径(默认/, 指定路径时必须以/结尾)
      storage-path: '~/youlan/'
      # 是否开始存储记录
      record-enabled: true
      # 存储记录缓存时间(s)
      record-cache-timeout: 1800
    # 操作日志
    operation-log:
      # 是否开启操作日志
      enabled: true
      # 是否开启位置查询
      region-enabled: true
      # 是否异步处理
      async-enabled: true
      # 异常信息保存长度上限
      error-length-limit: 200

--- # 公共模块
youlan:
  common:
    # 加密
    crypto:
      # AES秘钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      aes-key: 85SylH6RnDL9H9a/yoqXew==
      # RSA公钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      rsa-public-key: classpath:crypto/rsa-public.key
      # RSA秘钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      rsa-private-key: classpath:crypto/rsa-private.key
      # SM2公钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      sm2-public-key: classpath:crypto/sm2-public.key
      # SM2私钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      sm2-private-key: classpath:crypto/sm2-private.key
      # SM2秘钥(支持明文秘钥/系统路径文件[需指定绝对路径]/类路径文件[需添加classpath:前缀])
      sm4-key: XZAzFuMtViu55dngoUVivQ==

--- # 插件模块
youlan:
  plugin:
    region:
      # ip2region 查询模式(FILE-基于文件 INDEX-基于索引 MEMORY-基于内存 NETWORK-基于网络)
      searcher-model: MEMORY
      # ip2region.xdb文件路径,类路径文件需添加classpath:前缀，如classpath:ip2region/ip2region.xdb
      xdb-path: classpath:ip2region/ip2region.xdb

# 服务配置
server:
  # 服务器的HTTP端口
  port: 4085
  # servlet配置
  servlet:
    # 应用的访问路径
    context-path: /
  # undertow配置
  undertow:
    # POST请求内容的最大大小，当值为-1时，默认值是无限的
    max-http-post-size: -1
    # 每个缓冲区的大小，越小的空间被利用越充分，默认值来源于JVM可用的最大内存量
    buffer-size: 1024
    # 是否在Java堆之外分配缓冲区，默认值来源于JVM可用的最大内存量。
    direct-buffers: true
    threads:
      # 执行非阻塞的任务线程数，它们会负责多个连接，默认设置每个CPU核心一个线程，不可设置过大，否则启动项目会报错：打开文件数过多
      io: 8
      # 阻塞任务线程池，当执行类似servlet请求阻塞IO操作，undertow会从这个线程池中取得线程，它的值取决于系统的负载
      worker: 256

# spring配置
spring:
  application:
    name: 'youlan-admin'
  # 环境描述
  profiles:
    active: "dev"
  # servlet配置
  servlet:
    # 文件上传
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 国际化配置
  messages:
    # 国际化编码
    encoding: UTF-8
    # 国际化资源文件路径
    basename: i18n/messages
  # jackson配置
  jackson:
    # 日期格式化格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 日期时
    time-zone: GMT+8
    # 序列化时忽略空值属性
    default-property-inclusion: non_null
    # 序列化配置
    serialization:
      # 是否格式化输出
      indent-output: true
      # 忽略不能转换的对象
      fail-on-empty-beans: false
    # 反序列化配置
    deserialization:
      # json中有对象里不存在的属性是否失败
      fail-on-ignored-properties: false
  arthas:
    # 是否开启arthas
    enabled: false

# MyBatisPlus配置
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.youlan.**.entity
  # 对应的XML文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  # 是否检查XML文件是否存在，默认不检查
  check-config-location: false
  # 基础配置
  configuration:
    # 是否开启Mybatis二级缓存，默认为true
    cache-enabled: true
    # 详细日志输出 org.apache.ibatis.logging.stdout.StdOutImpl
    # 关闭日志输出 org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 默认日志输出 org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
  # 全局配置
  global-config:
    db-config:
      # 全局主键类型
      id-type: assign_id
      # 全局逻辑删除字段
      logic-delete-field: sts
      # 全局未逻辑删除值
      logic-not-delete-value: '1'
      # 全局已逻辑删除值
      logic-delete-value: '2'

# 接口文档配置
springdoc:
  # 文档配置
  api-docs:
    # 是否开启接口文档
    enabled: true
    # 接口文档路径
    path: /v3/api-docs
  # swagger配置
  swagger-ui:
    # swagger地址
    path: /swagger-ui.html
    # tag排序
    tags-sorter: alpha
    # operation排序
    operations-sorter: alpha
  group-configs:
    - group: '1.系统管理模块'
      paths-to-match: '/**'
      packages-to-scan: 'com.youlan.controller.system'
    - group: '2.系统工具模块'
      paths-to-match: '/**'
      packages-to-scan: 'com.youlan.controller.tools'

# Knife4j配置
knife4j:
  # 是否开启
  enable: true
  # 基础设置
  setting:
    language: zh_cn
    swagger-model-name: "实体类列表"

# SaToken配置
sa-token:
  # token 名称
  token-name: token
  # token 有效期(s)
  timeout: 259200
  # token 最低活跃频率(s)
  active-timeout: -1
  # 是否允许统一账号多地同时登录
  is-concurrent: true
  # 在多人登录同一账号时, 是否公共一个token
  is-share: true
  # token 风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# Arthas配置
arthas:
  # 端口为0则不开启http端口(生产环境请慎重配置)
  http-port: 18564
  # 端口为0则不开启telnet端口(生产环境请慎重配置)
  telnet-port: 18565
  # 代理ID
  agent-id: 'arthas-admin'

# Actuator端点配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: ./logs/info.log
      enabled: true